{
  gtk4,
  writeScript,
  makeSetupHook,
  vscode,
  vscode-utils,
  vscode-extensions,
  vscode-with-extensions,
  volar-pkgs,
  ...
}: vscode-with-extensions.override {
  vscodeExtensions = with vscode-extensions; [
    llvm-vs-code-extensions.vscode-clangd
    justusadam.language-haskell
    wakatime.vscode-wakatime
    myriad-dreamin.tinymist
    rust-lang.rust-analyzer
    saoudrizwan.claude-dev
    mesonbuild.mesonbuild
    vadimcn.vscode-lldb
    github.copilot-chat
    banacorn.agda-mode
    jnoortheen.nix-ide
    scala-lang.scala
    scalameta.metals
    adpyke.codesnap
    eamodio.gitlens
    haskell.haskell
    github.copilot
    tomoki1207.pdf
    vscodevim.vim
    bbenoist.nix
    mkhl.direnv
    volar-pkgs.vscode-extensions.vue.volar
    golang.go
  ];
}
