{
  vscode-utils,
  vscode-extensions,
  vscode-with-extensions,
  ...
}: vscode-with-extensions.override {
  vscodeExtensions = with vscode-extensions; [
    llvm-vs-code-extensions.vscode-clangd
    justusadam.language-haskell
    wakatime.vscode-wakatime
    myriad-dreamin.tinymist
    rust-lang.rust-analyzer
    mgt19937.typst-preview
    mesonbuild.mesonbuild
    vadimcn.vscode-lldb
    banacorn.agda-mode
    jnoortheen.nix-ide
    scala-lang.scala
    adpyke.codesnap
    eamodio.gitlens
    haskell.haskell
    github.copilot
    tomoki1207.pdf
    vscodevim.vim
    prisma.prisma
    bbenoist.nix
    mkhl.direnv
    vue.volar
  ];
}